### ISSUE TITLE
Design Docs Review #1

### ISSUE THREAD

**Issue by jliversi** [davidjhinku/Dinnr#1]
Great start on your design docs, here are my notes so far:
**MVP LIST**
- [x] Very well fleshed out
- [x] The one note I have is for restaurants, leave ownership and creation to a bonus. Focus on the customer side of open table and your main CRUD will be reviews

**SCHEMA**
- [x] You're currently missing a few columns you'll need on restaurants: cuisine_type , price_range, lat and lng (for maps). (Also should `has_many` business_hours)
- [x] Re previous note's cuisine_type: is that what `restaurant_categories` is? If so, do you need this to be a joins table? Looking through OpenTable, it looks like restaurants only have one each. 
- [x] For timeslots, it's going to be much easier to manage if instead of having their own table, they're just calculated at the time based on existing reservations, so I'd recommend removing that table 
- [x] Reservation should have a user_id
- [x] Is`menu_categories` things like lunch, dinner, etc? If so, this can just be another row on menus and doesn't need to be its own joins table.

**Comment by davidjhinku** [comment]
**MVP List**
- Updated to move all restaurant creation/management to Bonus 7

**SCHEMA**
- 1: Updated missing columns and association.
- 2: Table for [Bonus 4](https://github.com/davidjhinku/Dinnr/wiki/MVP-List#bonus-4-discoverexplore) where users are recommended restaurants based on a multiple attributes quiz (cuisines_types, fast casual, romantic, family, burgers etc). `cuisine_type` added to restaurants table and categories/attributes table added to bonus list
- 3: Timeslot table removed and associations/foreign_keys have been updated
- 4: Foreign_keys updated
- 5: Menu categories table removed, existing `name` column will function as an indicator of lunch, dinner etc. Joins table added for many-to-many relationships between menu and items (burgers can be on the lunch and dinner menu)
