### ISSUE TITLE
Design Docs Review #2

### ISSUE THREAD

**Issue by jliversi** [davidjhinku/Dinnr#2]
Very nice work on these docs, they're very fleshed out, and your notes are clear. 

**SAMPLE STATE**
- [x] Add any changes from schema (ex. adding cuisine_type to restaurants) 
- [x] To your note on minutes for openAt and closeAt, can you make that time a float instead of an integer? 

**BACKEND ROUTES**
- [x] Just on an organizational note, it may make your workflow easier to sort all owner-only routes into their own section (as you won't be using these for the first 7 MVPs of your project)

**FRONTEND ROUTES & COMPONENTS** 
- [x] Only note here is the same as for backend routes.

**Comment by davidjhinku** [comment]
**SAMPLE**
- Updated to remove old tables
- Data refreshed for new columns and edited columns
- Schema and Sample updated to represent a open/close time as a float

**BACK/FRONTEND**
- Routes related to restaurant management(creation, menu, items) have been moved to a bonus section at the bottom of the page with a link to the MVP bonus
- Routes updated for tables that have been removed or edited
