### ISSUE TITLE
MVP Review 2. New account creation, login, and guest/demo login

### ISSUE THREAD

**Issue by davidjhinku** [davidjhinku/Dinnr#3]
[Heroku Link](https://dinnr-aa.herokuapp.com/#/)

Notes:
- Looking to add further styling to `Demo User` button to differentiate from `Sign In`
- Will add 1px border to Nav `Sign Up` button to match size of `Sign In` button

**Comment by jliversi** [comment]
- [x] Add a image to your main splash page.
- [x] Otherwise, everything is perfect.
